Message {
  channel:
   TextChannel {
     id: '184268959003049989',
     client:
      Client {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        options: [Object],
        internal: [Object] },
     name: 'general',
     type: 'text',
     position: 0,
     permissionOverwrites: Cache { limit: undefined },
     server:
      Server {
        client: [Object],
        region: 'us-central',
        ownerID: '154928746636378112',
        name: 'FFC_Test_Server',
        id: '184268959003049989',
        members: [Object],
        channels: [Object],
        roles: [Object],
        icon: '2415de5076dcfcb0fd0909f11ff7751b',
        afkTimeout: 300,
        afkChannelID: undefined,
        memberMap: [Object],
        memberCount: 4,
        large: false },
     topic: '',
     lastMessageID: '198649474032205824',
     messages: Cache { '0': [Circular], limit: 1000, length: 1 } },
  server:
   Server {
     client:
      Client {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        options: [Object],
        internal: [Object] },
     region: 'us-central',
     ownerID: '154928746636378112',
     name: 'FFC_Test_Server',
     id: '184268959003049989',
     members:
      Cache {
        '0': [Object],
        '1': [Object],
        '2': [Object],
        '3': [Object],
        limit: undefined,
        length: 4 },
     channels: Cache { '0': [Object], '1': [Object], limit: undefined, length: 2 },
     roles: Cache { '0': [Object], '1': [Object], limit: undefined, length: 2 },
     icon: '2415de5076dcfcb0fd0909f11ff7751b',
     afkTimeout: 300,
     afkChannelID: undefined,
     memberMap:
      { '154928746636378112': [Object],
        '184374205528276992': [Object],
        '184495173667913729': [Object],
        '198105044992655370': [Object] },
     memberCount: 4,
     large: false },
  client:
   Client {
     domain: null,
     _events: { message: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     options:
      { compress: true,
        autoReconnect: false,
        rateLimitAsError: false,
        largeThreshold: 250,
        maxCachedMessages: 1000,
        guildCreateTimeout: 1000,
        shardId: 0,
        shardCount: 0,
        disableEveryone: false },
     internal:
      InternalClient {
        client: [Circular],
        state: 3,
        websocket: [Object],
        userAgentInfo: [Object],
        users: [Object],
        friends: null,
        blocked_users: null,
        outgoing_friend_requests: null,
        incoming_friend_requests: null,
        channels: [Object],
        servers: [Object],
        unavailableServers: [Object],
        private_channels: [Object],
        autoReconnectInterval: 1000,
        intervals: [Object],
        voiceConnections: [Object],
        resolver: [Object],
        readyTime: 1467432119853,
        messageAwaits: {},
        retryAfters: {},
        tokenCacher: [Object],
        token: 'MTk4MTA1MDQ0OTkyNjU1Mzcw.ClbTMw.vy3yVmW3--r7UUXHFWDLB1DLK6E',
        email: null,
        password: null,
        gatewayURL: 'wss://gateway.discord.gg',
        user: [Object],
        forceFetchCount: {},
        forceFetchQueue: [],
        forceFetchLength: 1,
        sessionID: '1599452122de6ce88cdf93f1079cb080',
        guildCreateTimeout: [Object] } },
  nonce: '198649483259543552',
  attachments: [],
  tts: false,
  embeds: [],
  timestamp: 1467432125338,
  everyoneMentioned: undefined,
  id: '198649474032205824',
  author:
   User {
     client:
      Client {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        options: [Object],
        internal: [Object] },
     username: 'Unisys12',
     discriminator: '5080',
     id: '154928746636378112',
     avatar: '1cb7f50fc70873fd6a83024289fb5117',
     bot: false,
     status: 'online',
     game: { type: 0, name: 'Sublime Text' },
     typing: { since: 1467432126499, channel: [Object] },
     voiceChannel: null,
     voiceState: {} },
  content: 'Once again, I would like to say hello!',
  cleanContent: 'Once again, I would like to say hello!',
  mentions: [] }
